/**
 * Texto da Deliberação SP-Águas nº 10, de 23 de setembro de 2025 (Experimento Regulatório
 * do Protocolo de Escassez Hídrica), um parágrafo por item, na ordem do documento.
 */

/** Preâmbulo: autoridade e considerandos. */
export const PREAMBULO: string[] = [
  "O Conselho Diretor da Agência de Águas do Estado de São Paulo - SP-ÁGUAS, na forma da Lei Complementar n.º 1.413, de 23 de setembro de 2024, regulamentada pelo Decreto nº 69.339, de 4 de fevereiro de 2025:",
  "Considerando a Lei n.º 6.134, de 2 de junho de 1988, que dispõe sobre a preservação dos depósitos naturais de águas subterrâneas, disciplinando seu uso racional;",
  "Considerando o artigo 22 do Decreto n.º 32.955, de 07 de fevereiro 1991, que, ao regulamentar a Lei n.º 6.134, de 02 de junho 1988, atribuiu ao Departamento de Águas e Energia Elétrica - DAEE o dever de estabelecer a proibição de novas captações até que o aquífero se recupere e de restringir e regular a captação de água subterrânea, estabelecendo volume máximo a ser extraído e o regime de operação;",
  "Considerando o artigo 9° da Lei n.º 7.663, de 30 de dezembro de 1991, que atribuiu a competência ao Departamento de Águas e Energia Elétrica – DAEE para autorizar a implantação de empreendimentos que demandem o uso de recursos hídricos, bem como outorgar o direito de uso;",
  "Considerando o disposto no artigo 15 da Lei federal nº 9.433, de 8 de janeiro de 1997, que estabeleceu as circunstâncias em que a outorga de direito de uso de recursos hídricos poderá ser suspensa parcial ou totalmente, em definitivo ou por prazo determinado, inclusive nos casos de necessidade premente de água para atender a situações de calamidade, incluídas as decorrentes de condições climáticas adversas, bem como nos casos de prevenir ou reverter grave degradação ambiental e de atender a usos prioritários, de interesse coletivo, para os quais não se disponha de fontes alternativas;",
  "Considerando a Lei n.º 9.866, de 28 de novembro de 1997, que dispõe sobre diretrizes e normas para a proteção e recuperação da qualidade ambiental das bacias hidrográficas dos mananciais de interesse regional para abastecimento das populações atuais e futuras do Estado de São Paulo, assegurados, desde que compatíveis, os demais usos múltiplos;",
  "Considerando a Lei n.º 16.337, de 14 de dezembro de 2016, que estabeleceu diretrizes e critérios gerais para a elaboração, implementação e monitoramento do Plano Estadual de Recursos Hídricos - PERH, determinando a prevenção e a mitigação de situações de escassez como uma de suas principais diretrizes;",
  "Considerando a Portaria DAEE n° 4.905, de 09 de setembro de 2019, que define os procedimentos que disciplinam a fiscalização de usos e interferências em recursos hídricos de domínio do Estado de São Paulo, bem como o enquadramento das infrações e as respectivas penalidades;",
  "Considerando que o artigo 68, incisos I e II, da Lei Complementar nº 1.413/2024, estabeleceu que a Agência de Águas do Estado de São Paulo – SP-ÁGUAS é competente para promover, controlar, fiscalizar e regular as outorgas do direito de uso de recursos hídricos, bem como o cadastro de seus usuários, inclusive nas hipóteses de dispensa, e para promover a segurança hídrica no território do Estado, fiscalizando e regulando as atividades para tanto necessárias, inclusive o controle de cheias, e prestando apoio técnico, quando couber, aos Municípios;",
  "Considerando as contribuições recebidas na Consulta Pública nº 03/2025 e a necessidade de que a presente deliberação seja tratada como regulação experimental, destinada à validação do modelo normativo mediante monitoramento contínuo e avaliação periódica, de modo a assegurar a efetividade, a segurança jurídica e o aprimoramento progressivo dos instrumentos de gestão de recursos hídricos; e",
  "Considerando o estudo técnico Diretrizes para Gestão em Situação de Escassez Hídrica (Relatório SEI nº 0070055847), a Nota Técnica SEI n° 0070014201 e as manifestações constantes no Processo SEI 137.00004407/2025-27,",
];

/** Artigos, parágrafos, incisos e alíneas; os objetos são os títulos de capítulo e seção. */
export const DISPOSITIVOS: (string | { titulo: string; subtitulo: string })[] = [
  { titulo: "CAPÍTULO I", subtitulo: "Do Objeto e Abrangência" },
  "Artigo 1° - Fica estabelecido o Experimento Regulatório no âmbito das bacias hidrográficas do Estado de São Paulo para implementação do Protocolo de Escassez Hídrica, consistente no conjunto de regras para disciplinar a atuação da SP-ÁGUAS no monitoramento da DISPONIBILIDADE HÍDRICA, na identificação de RISCOS e na implementação de MEDIDAS DE CONTINGÊNCIA.",
  "Artigo 2° - As disposições desta deliberação aplicam-se às unidades internas da SP- ÁGUAS, nos limites de suas competências regimentais.",
  { titulo: "CAPÍTULO II", subtitulo: "Das Definições" },
  "Artigo 3° - Para fins desta deliberação, serão adotadas as seguintes definições:",
  "I - ATO NORMATIVO ESPECÍFICO: Portaria DAEE n° 4.905, de 09 de setembro de 2019 e suas posteriores revisões pela SP-ÁGUAS;",
  "II - DECLARAÇÃO DE DISPENSA DE OUTORGA: ato administrativo, emitido pela SP-ÁGUAS, para usos e interferências em recursos hídricos que são considerados insignificantes, disciplinados em regulamento;",
  "III - DECLARAÇÃO DE ESCASSEZ HÍDRICA: ato administrativo emitido pela SP-ÁGUAS, por meio de deliberação do Conselho Diretor, que reconhece a ocorrência de situação de escassez de água em uma região, evidenciando o desequilíbrio entre oferta e demanda de recursos hídricos, resultando na implementação de medidas de contingência ao uso da água;",
  "IV - DECLARAÇÃO DE VIABILIDADE DE IMPLANTAÇÃO DE EMPREENDIMENTO (DVI): documento que pode ser emitido pela SP-ÁGUAS a partir de análise de solicitação de interesse em obter futura OUTORGA para obra ou empreendimento que esteja em fase de planejamento ou projeto, e que oferece, durante seu período de validade, garantia de DISPONIBILIDADE HÍDRICA;",
  "V - DISPONIBILIDADE HÍDRICA: quantidade de água disponível em uma região para ser utilizada para diversos fins, como consumo humano, agrícola e industrial, levando em consideração a qualidade e o tempo de renovação das fontes hídricas;",
  "VI - ESCASSEZ HÍDRICA: condição de desequilíbrio quantitativo entre oferta e demanda de água em um domínio hidrográfico específico como resultado de uma alta demanda em comparação com a oferta disponível;",
  "VII - EXPERIMENTO REGULATÓRIO: é um mecanismo temporário de aplicação normativa, que permite testar e avaliar modelos, procedimentos ou instrumentos de regulação, mediante monitoramento contínuo e avaliação periódica, visando à validação, ao aperfeiçoamento e à segurança jurídica da política pública;",
  "VIII - MEDIDAS DE CONTINGÊNCIA: medidas de resposta frente ao RISCO que variam de acordo com os estágios de DISPONIBILIDADE HÍDRICA;",
  "IX - OUTORGA: ato administrativo, praticado por meio de autorização ou de concessão, com prazo determinado, mediante o qual a SP-ÁGUAS defere a utilização ou interferência em recursos hídricos, após solicitação formal do requerente, nos termos e nas condições expressas em norma específica, considerando aspectos técnicos e legais previstos em regulamento;",
  "X - PRECIPITAÇÃO: consiste na queda de água do estado líquido ou sólido da atmosfera em direção à superfície terrestre;",
  "XI - RISCO: probabilidade de ocorrência de eventos que afetem a disponibilidade hídrica, causando prejuízos econômicos, sociais ou ambientais;",
  "XII - SECA: ausência prolongada ou deficiência acentuada de PRECIPITAÇÃO ou período anormalmente seco, suficientemente prolongado para que a sua falta cause um desequilíbrio hidrológico grave;",
  "XIII - UGRHI: Unidade de Gerenciamento de Recursos Hídricos e suas subdivisões (subUGRHI);",
  "XIV - USO NÃO PRIORITÁRIO: refere-se a todos os usos da água que não se destinam ao consumo humano ou à dessedentação de animais.",
  { titulo: "CAPÍTULO III", subtitulo: "Dos Procedimentos" },
  { titulo: "SEÇÃO I", subtitulo: "Do Monitoramento e Estágios de Disponibilidade Hídrica" },
  "Artigo 4° - O monitoramento e a avaliação da ESCASSEZ HÍDRICA será realizado por meio da análise de indicadores técnicos, que integram o Anexo Único desta Deliberação.",
  "Parágrafo único - Os resultados dos indicadores utilizados no monitoramento e na avaliação de RISCO ficarão disponíveis para acompanhamento no sítio eletrônico da SP-ÁGUAS: https://www.spaguas.sp.gov.br/.",
  "Artigo 5° - A avaliação da ESCASSEZ HÍDRICA abrangerá as 114 (cento e catorze) sub-UGRHIs do Estado de São Paulo.",
  "Artigo 6° - Conforme a avaliação dos indicadores técnicos, constituirão estágios de DISPONIBILIDADE HÍDRICA:",
  "I - Estágio 0: Situação de Normalidade;",
  "II - Estágio 1: Situação de Atenção;",
  "III - Estágio 2: Situação de Alerta;",
  "IV - Estágio 3: Situação Crítica;",
  "V - Estágio 4: Situação de Emergência.",
  "Parágrafo único - Os intervalos dos indicadores e as condições que definem o enquadramento nos estágios de DISPONIBILIDADE HÍDRICA constam no Anexo Único desta deliberação.",
  "Artigo 7° - Os estágios de DISPONIBILIDADE HÍDRICA serão avaliados mensalmente pelas áreas competentes da SP-ÁGUAS.",
  "Artigo 8° - A emissão da DECLARAÇÃO DE ESCASSEZ HÍDRICA pela SP-ÁGUAS ocorrerá a partir do enquadramento no Estágio 3 (Situação Crítica), considerada a fundamentação da DECLARAÇÃO DE ESCASSEZ HÍDRICA, na forma do artigo 9°.",
  "Parágrafo único - A DECLARAÇÃO DE ESCASSEZ HÍDRICA e sua revogação serão objeto de Deliberação do Conselho Diretor, a ser instruída por Nota Técnica com a análise de indicadores e dados de monitoramento, e por Nota Técnica com a fundamentação da DECLARAÇÃO DE ESCASSEZ HÍDRICA.",
  { titulo: "SEÇÃO II", subtitulo: "Da Fundamentação da Declaração de Escassez Hídrica" },
  "Artigo 9° - A fundamentação da DECLARAÇÃO DE ESCASSEZ HÍDRICA de que trata o artigo 8° desta deliberação ocorrerá por meio de análise integrada de aspectos qualitativos e quantitativos, contemplando, sempre que aplicável, as dimensões de exposição, sensibilidade e capacidade de resposta institucional, de modo a fundamentar a DECLARAÇÃO DE ESCASSEZ HÍDRICA e a adoção de MEDIDAS DE CONTINGÊNCIA proporcionais e adequadas.",
  "§ 1° - A análise deverá considerar, de forma articulada, séries históricas de afluências, projeções climáticas, volumes armazenados, cotas de operação e regras de outorga, podendo incluir, quando aplicável, a caracterização dos diferentes usos da água e a segmentação espacial das captações em relação aos mananciais e estruturas de controle.",
  "§ 2° - Poderão ser desenvolvidos cenários prospectivos de evolução da DISPONIBILIDADE HÍDRICA, com e sem a adoção de medidas adicionais, de modo a estimar impactos setoriais da escassez e indicar alternativas de resposta compatíveis com as condições observadas, assegurada a priorização do abastecimento humano e da dessedentação animal, conforme previsto em lei.",
  "§ 3° - Sempre que necessário, a análise poderá incluir a avaliação da vulnerabilidade de populações mais expostas, a estimativa de atendimento dos usos prioritários e a apreciação da capacidade institucional de resposta da bacia.",
  { titulo: "SEÇÃO III", subtitulo: "Das Medidas de Contingência" },
  "Artigo 10 - Em cada estágio de DISPONIBILIDADE HÍDRICA poderão ser adotadas as seguintes medidas:",
  "I - Estágio 0 – Situação de Normalidade;",
  "II - Estágio 1 – Situação de Atenção:",
  "a) intensificação do monitoramento realizado na Situação de Normalidade;",
  "b) fiscalização com ações dirigidas.",
  "III - Estágio 2 – Situação de Alerta:",
  "a) todas do Estágio 1 – Situação de Atenção;",
  "b) intensificação na fiscalização de grandes usuários, conforme definido pela Superintendência de Fiscalização;",
  "c) interlocução com os Comitês de Bacias Hidrográficas e lideranças comunitárias a respeito dos estágios de DISPONIBILIDADE HÍDRICA e das MEDIDAS DE CONTINGÊNCIA em curso;",
  "d) levantamento e divulgação da quantidade de usuários e das vazões outorgadas para os usos sujeitos às restrições de OUTORGAS previstas nos estágios 3 e 4 (dados agregados).",
  "IV - Estágio 3 – Situação Crítica:",
  "a) todas do Estágio 2 – Situação de Alerta;",
  "b) priorização dos processos de concessão de OUTORGA emergencial e sazonal para os usos prioritários;",
  "c) suspensão da emissão de novas declarações de dispensa de OUTORGA de captação superficial para USOS NÃO PRIORITÁRIOS;",
  "d) suspensão da emissão de novas OUTORGAS de captação superficial para USOS NÃO PRIORITÁRIOS;",
  "e) suspensão da emissão de novas OUTORGAS de captação subterrânea realizadas por poços escavados (cacimbas e cisternas) e para poços tubulares com até 30 metros de profundidade, quando localizados a menos de 200 metros de corpos hídricos, para USOS NÃO PRIORITÁRIOS;",
  "f) adequação de OUTORGAS de captação superficial, com redução de vazão outorgada, aplicada a USOS NÃO PRIORITÁRIOS;",
  "g) adequação de OUTORGAS de captação subterrânea para USOS NÃO PRIORITÁRIOS realizadas por poços escavados (cacimbas e cisternas) e para poços tubulares com até 30 metros de profundidade, quando localizados a menos de 200 metros de corpos hídricos, através da definição de limite máximo de captação temporário que seja abaixo da vazão outorgada;",
  "h) intensificação da fiscalização do cumprimento das adequações de outorgas estabelecidas nas alíneas anteriores, com foco na verificação do respeito aos limites temporários de captação e à redução de vazões outorgadas para os USOS NÃO PRIORITÁRIOS.",
  "V - Estágio 4 – Situação de Emergência:",
  "a) todas do Estágio 3 – Situação Crítica;",
  "b) adequação de vazão de OUTORGAS emitidas para captação superficial para o abastecimento público, inclusive com redução de vazões outorgadas.",
  "§ 1° - A suspensão de emissão de novas OUTORGAS, adequações ou suspensões de OUTORGA seguirá a ordem prevista no Plano de Bacia Hidrográfica ou, na ausência deste, no que estabelece o disposto no Artigo 12 da Lei n.º 16.337, de 14 de dezembro de 2016.",
  "§ 2° - A adoção das MEDIDAS DE CONTINGÊNCIA previstas no artigo 10 desta Deliberação será articulada com os usuários, Comitês de Bacia Hidrográfica e demais órgãos e entidades do SIGRH e do SINGREH.",
  "Artigo 11 - A adoção de MEDIDAS DE CONTINGÊNCIA, por determinação do Conselho Diretor, a partir do estágio 3, será precedida de DECLARAÇÃO DE ESCASSEZ HÍDRICA e poderá ser adaptada conforme a realidade local e a gravidade da situação.",
  { titulo: "SEÇÃO IV", subtitulo: "Da Comunicação" },
  "Artigo 12 - Serão empregados os seguintes meios oficiais para a comunicação dos estágios de DISPONIBILIDADE HÍDRICA e das MEDIDAS DE CONTINGÊNCIA adotadas pela SP-ÁGUAS:",
  "I – publicação em seu sítio eletrônico e mídias digitais e sociais oficiais;",
  "II – boletins técnicos regulares com indicadores atualizados;",
  "III – comunicados oficiais enviados aos entes federativos, agências reguladoras, operadores de sistemas e usuários regulados;",
  "IV – participação em reuniões técnicas e colegiados do Sistema Integrado de Gerenciamento de Recursos Hídricos – SIGRH e do Sistema Nacional de Gerenciamento de Recursos Hídricos – SINGREH.",
  "Parágrafo único - Os usuários outorgados serão comunicados de maneira direta e individualizada caso venham a ser atingidos por MEDIDA DE CONTINGÊNCIA decorrentes dos ESTÁGIOS DE DISPONIBILIDADE HÍDRICA de que trata esta Deliberação.",
  "Artigo 13 - A comunicação deverá destacar, de forma clara e didática:",
  "I – o ESTÁGIO DE DISPONIBILIDADE HÍDRICA e seus critérios técnicos;",
  "II – as MEDIDAS DE CONTINGÊNCIA recomendadas ou impostas, conforme o caso;",
  "III – as orientações aos usuários sobre o uso racional da água;",
  "IV – as possíveis consequências do agravamento da escassez;",
  "V - outras informações relevantes para o atingimento dos objetivos.",
  "Artigo 14 - Quando a DISPONIBILIDADE HÍDRICA atingir a Situação de Emergência (Estágio 4), a comunicação poderá ser reforçada com campanhas específicas, ações de esclarecimento à população e ampla articulação com os meios de comunicação de massa.",
  "Artigo 15 - As ações de comunicação deverão ser integradas com outros órgãos públicos envolvidos na gestão de recursos hídricos e defesa civil, assim como a Secretaria de Comunicação, de forma a garantir mensagens coerentes e coordenadas.",
  "Artigo 16 - Compete à Superintendência de Segurança Hídrica comunicar formalmente ao Conselho Diretor o enquadramento das subUGRHIs nos Estágio 3 (Situação Crítica) e Estágio 4 (Situação de Emergência), para fins de adoção de providências operacionais e administrativas pertinentes, inclusive DECLARAÇÃO DE ESCASSEZ, em conformidade com as diretrizes estabelecidas.",
  { titulo: "CAPÍTULO IV", subtitulo: "Do Experimento Regulatório" },
  { titulo: "SEÇÃO I", subtitulo: "Da Operacionalização" },
  "Artigo 17 - A operacionalização do EXPERIMENTO REGULATÓRIO observará os estágios de DISPONIBILIDADE HÍDRICA, cabendo à SP-ÁGUAS aplicar e validar, em caráter experimental, os indicadores e as condições estabelecidas no Anexo Único para cada estágio nas subUGRHIs.",
  "Artigo 18 - Compete à Assessoria de Qualidade Regulatória acompanhar a execução do Experimento Regulatório, consolidar as informações produzidas pelas áreas técnicas, coordenar a sistematização das evidências e elaborar relatórios de avaliação periódica, a serem submetidos ao Conselho Diretor, garantindo a transparência e a previsibilidade necessárias ao processo regulatório.",
  { titulo: "SEÇÃO II", subtitulo: "Das Cláusulas de Suspensão" },
  "Artigo 19 - A aplicação do EXPERIMENTO REGULATÓRIO poderá ser suspensa, total ou parcialmente, por decisão do Conselho Diretor, após as manifestações das áreas técnicas, considerando interesse público, prudência regulatória ou necessidade de reavaliação metodológica.",
  "Artigo 20 - A decisão de suspensão fixará as condições para sua revisão ou revogação.",
  "Artigo 21 - Durante o período de suspensão, permanecem aplicáveis:",
  "I – as obrigações essenciais das OUTORGAS de uso da água;",
  "II – a coleta de informações necessárias à avaliação de RISCOS e à continuidade do monitoramento;",
  "III – quaisquer MEDIDAS DE CONTINGÊNCIA impostas para garantir a segurança hídrica.",
  { titulo: "CAPÍTULO V", subtitulo: "Das Obrigações" },
  "Artigo 22 - O caráter experimental deste normativo não implica no afastamento das obrigações previstas nas OUTORGAS de uso de recursos hídricos, nem exclui a possibilidade de aplicação das medidas administrativas cabíveis em caso de descumprimento da legislação.",
  "Artigo 23 - A aplicação de medidas administrativas seguirá o procedimento estabelecimento no ATO NORMATIVO ESPECÍFICO.",
  { titulo: "CAPÍTULO VI", subtitulo: "Disposições Finais" },
  "Artigo 24 - Encerrado o prazo de vigência do EXPERIMENTO REGULATÓRIO, o Conselho Diretor decidirá, com base em relatório final das áreas competentes, pela consolidação e publicação definitiva do Protocolo de ESCASSEZ HÍDRICA, pela prorrogação do EXPERIMENTO REGULATÓRIO ou pela revogação deste ato.",
  "Artigo 25 - Esta Deliberação, de caráter experimental, vigorará por 24 (vinte e quatro) meses, contados da data de sua publicação.",
];

/** Anexo Único, item 1: título, definições dos indicadores e observação final. */
export const ANEXO_DEFINICOES: string[] = [
  "1. Definições dos indicadores técnicos",
  "I - Anomalia de PRECIPITAÇÃO: comparativo dos valores absolutos e percentuais observados com a média histórica, indicando períodos de déficit ou excesso de chuva, para identificar desvios sazonais, auxiliando na detecção de eventos críticos de SECAS ou períodos de PRECIPITAÇÃO extrema;",
  "II - Cota de permanência (fluviometria): obtido por meio da plataforma Sistema Integrado de Bacias Hidrográficas (SIBH) da SP-ÁGUAS, permite o acompanhamento contínuo dos níveis dos cursos d’água, fornecendo subsídios essenciais para a gestão de eventos hidrológicos críticos, como SECAS e estiagens prolongadas;",
  "III - Duração da SECA: métrica que quantifica a persistência de uma SECA em uma determinada região e permite diferenciar SECAS pontuais de eventos prolongados e potencialmente danosos;",
  "IV - Índice de Precipitação e Evapotranspiração Padronizado (SPEI): incorpora a PRECIPITAÇÃO e a evapotranspiração na avaliação da SECA, permitindo captar os efeitos do aumento das temperaturas na demanda hídrica;",
  "V - Índice de Precipitação Padronizada (SPI): comparativo entre diferentes regiões e datas numa mesma base de cálculo, classificando-as em normal, SECA fraca, SECA moderada, SECA grave, SECA extrema e SECA excepcional. Além de umidade fraca, umidade moderada, umidade grave, umidade extrema e umidade excepcional;",
  "VI - Índice de Vegetação por Diferença Normalizada - NDVI: índice derivado de dados de sensoriamento remoto, utilizado para estimar a vigor vegetativo com base na atividade fotossintética da vegetação monitorada;",
  "VII - Monitor de Secas da Agência Nacional de Águas e Saneamento Básico (ANA): sistema de monitoramento contínuo da intensidade das SECAS no Brasil, fundamentado em indicadores climáticos e nos efeitos do fenômeno a curto e longo prazo;",
  "VIII – Volume útil dos reservatórios: obtido por meio do Sistema de Suporte à Decisão (SSD) Sistema Produtores da SP-ÁGUAS, que monitora o nível, volume, vazão e chuva dos reservatórios Cantareira, Paraíba do Sul, Cotia, São Lourenço, Guarapiranga, Billings, Rio Grande, Alto Tietê e Rio Claro, fornecendo um indicativo sobre a capacidade de atendimento do reservatório considerando a demanda hídrica da sua região de abrangência.",
  "Os indicadores SPI, SPEI e anomalia de precipitação, com o sufixo “6”, referem-se à análise de seis meses, permitindo identificar tendências de médio prazo para gestão de ESCASSEZ HÍDRICA e monitoramento hidrológico e climático.",
];

/** Anexo Único, item 2: condições de enquadramento em cada estágio ([indicador, condição]). */
export const ANEXO_ESTAGIOS_TITULO = "2 - Condições de enquadramento nos estágios de disponibilidade hídrica";
export const ANEXO_ESTAGIOS: { n: number; nome: string; intro: string; linhas: [string, string][] }[] = [
  {
    n: 0,
    nome: "Situação de Normalidade",
    intro: "os indicadores apresentam as seguintes condições:",
    linhas: [
      ["Monitor de secas da ANA", "Sem seca relativa"],
      ["Índice de Precipitação Padronizada (SPI)", "SPEI 6 > -0,524"],
      ["Índice de Precipitação e Evapotranspiração Padronizado (SPEI)", "SPI 6 > -0,524"],
      ["Anomalia de precipitação", "Anomalia de precipitação 6 > -10%"],
      ["Volume útil dos reservatórios", "Volume útil > 60%"],
    ],
  },
  {
    n: 1,
    nome: "Situação de Atenção",
    intro: "é indicado por, ao menos, uma das seguintes condições:",
    linhas: [
      ["Monitor de secas da ANA", "Seca fraca com impacto de curta duração"],
      ["Índice de Precipitação Padronizada (SPI)", "-1,282 < SPI ≤ -0,524"],
      ["Índice de Precipitação e Evapotranspiração Padronizado (SPEI)", "-1,282 < SPEI ≤ -0,524"],
      ["Anomalia de precipitação", "-30% < Anomalia de precipitação 6 ≤ -10%"],
      ["Volume útil dos reservatórios", "40% < Volume útil ≤ 60%"],
    ],
  },
  {
    n: 2,
    nome: "Situação de Alerta",
    intro: "é indicado por, ao menos, uma das seguintes condições:",
    linhas: [
      ["Monitor de secas da ANA", "Seca moderada com impacto de curta duração"],
      ["Índice de Precipitação Padronizada (SPI)", "-1,645 < SPI ≤ -1,282"],
      ["Índice de Precipitação e Evapotranspiração Padronizado (SPEI)", "-1,645 < SPEI ≤ -1,282"],
      ["Anomalia de precipitação", "-50% < Anomalia de precipitação 6 ≤ -30%"],
      ["Volume útil dos reservatórios", "30% < Volume útil ≤ 40%"],
      ["Cota de permanência (fluviometria)", "Cota de permanência ≤ N90"],
      ["Duração da seca", "Duração da seca > 6 meses"],
      ["Desvio de NDVI", "-15% < Desvio de NDVI ≤ -5%"],
    ],
  },
  {
    n: 3,
    nome: "Situação Crítica",
    intro: "é indicado por, ao menos, uma das seguintes condições:",
    linhas: [
      ["Monitor de secas da ANA", "Seca grave com impacto de curta e/ou longa duração"],
      ["Índice de Precipitação Padronizada (SPI)", "-2,326 < SPI ≤ -1,645"],
      ["Índice de Precipitação e Evapotranspiração Padronizado (SPEI)", "-2,326 < SPEI ≤ -1,645"],
      ["Anomalia de precipitação", "-70% < Anomalia de precipitação 6 ≤ -50%"],
      ["Volume útil dos reservatórios", "20% < Volume útil ≤ 30%"],
      ["Cota de permanência (fluviometria)", "Cota de permanência ≤ N95"],
      ["Duração da seca", "Duração da seca > 12 meses"],
      ["Desvio de NDVI", "Desvio de NDVI ≤ -15%"],
    ],
  },
  {
    n: 4,
    nome: "Situação de Emergência",
    intro: "é indicado por, ao menos, uma das seguintes condições:",
    linhas: [
      ["Monitor de secas da ANA", "Seca extrema com impacto de longa duração"],
      ["Índice de Precipitação Padronizada (SPI)", "SPI ≤ -2,326"],
      ["Índice de Precipitação e Evapotranspiração Padronizado (SPEI)", "SPEI ≤ -2,326"],
      ["Anomalia de precipitação", "Anomalia de precipitação 6 ≤ -70%"],
      ["Volume útil dos reservatórios", "Volume útil ≤ 20%"],
      ["Cota de permanência (fluviometria)", "Cota de permanência ≤ N7,10"],
      ["Duração da seca", "Duração da seca > 18 meses"],
    ],
  },
];
