/**
 * Texto da Resolução Conjunta ANA/DAEE nº 925, de 29 de maio de 2017 (Sistema Cantareira),
 * um parágrafo por item, na ordem do documento.
 */

/** Preâmbulo: autoridades e considerandos. */
export const PREAMBULO: string[] = [
  "O DIRETOR-PRESIDENTE DA AGÊNCIA NACIONAL DE ÁGUAS – ANA, no uso da atribuição que lhe confere o art. 103, inciso IV e XII, do Regimento Interno aprovado pela Resolução nº 828, de 15 de maio de 2017, torna público que a DIRETORIA COLEGIADA, em sua 657ª Reunião Ordinária, realizada em 29 de maio de 2017, e o SUPERINTENDENTE DO DEPARTAMENTO DE ÁGUAS E ENERGIA ELÉTRICA - DAEE, do Estado de São Paulo, no uso de suas atribuições, definidas nos artigos 9º e 10º da Lei do Estado de São Paulo nº 7.663, de 30 de dezembro de 1991, tendo em vista os elementos constantes do Processo nº 02501.001114/2017-16, protocolado na ANA e dos Autos DAEE nº 9805040.",
  "Considerando o disposto no art. 4º, inciso XII, da Lei nº 9.984, de 17 de julho de 2000, que estabelece caber à ANA definir e fiscalizar as condições de operação de reservatórios por agentes públicos e privados, visando a garantir o uso múltiplo dos recursos hídricos, conforme estabelecido nos planos de recursos hídricos das respectivas bacias hidrográficas;",
  "Considerando o disposto no art. 4º da Lei nº 9.433, de 8 de janeiro de 1997, que estabelece que a União articular-se-á com os Estados tendo em vista o gerenciamento dos recursos hídricos de interesse comum;",
  "Considerando o art. 8º da Lei do Estado de São Paulo de nº 7.663, de 30 de dezembro de 1991, que estabelece que o Estado, observados os dispositivos constitucionais relativos à matéria, articular-se-á com a União, outros Estados vizinhos e municípios, para o aproveitamento e controle dos recursos hídricos em seu território;",
  "Considerando a importância do Sistema Cantareira para o abastecimento da Região Metropolitana de São Paulo e das Bacias dos rios Piracicaba, Capivari e Jundiaí – Bacias PCJ;",
  "Considerando os estudos feitos pela ANA e DAEE sobre o Sistema Cantareira, além do processo de consulta para estabelecimento das condições de operação estabelecidas nesta Resolução;",
  "Considerando o reconhecimento da importância dos impactos das mudanças climáticas sobre os recursos hídricos, especialmente no agravamento de eventos hidrológicos críticos e na alteração da estacionariedade das séries hidrológicas;",
];

/** Dispositivos (depois de "Resolvem:"): artigos, parágrafos e incisos. */
export const DISPOSITIVOS: string[] = [
  "Art. 1º Estabelecer condições de operação para o Sistema Cantareira - SC, delimitado, para os fins desta Resolução, como o conjunto dos reservatórios Jaguari-Jacareí, Cachoeira, Atibainha e Paiva Castro.",
  "§ 1º O volume útil total do Sistema Cantareira representa a soma dos volumes úteis operacionais existentes nos reservatórios Jaguari-Jacareí, Cachoeira, Atibainha e Paiva Castro, totalizando 981,56 hm³, conforme quadro a seguir:",
  "§ 2º A vazão de retirada do Sistema Cantareira é a vazão de transferência para a Região Metropolitana de São Paulo (RMSP) na Estação Elevatória de Santa Inês, acrescida da soma das vazões defluentes dos reservatórios de Jaguari-Jacareí, Cachoeira, Atibainha e Paiva Castro.",
  "§ 3º Caso seja necessário utilizar os volumes abaixo das cotas mínimas operacionais definidas no § 1º, a SABESP deverá obter autorização expressa dos órgãos gestores.",
  "Art. 2º Ficam definidos como limites para as vazões mínimas instantâneas a serem liberadas nos seguintes pontos de controle do Sistema Cantareira, os seguintes valores:",
  "I - Descarga para jusante do reservatório Paiva Castro no rio Juqueri: 0,10 m³/s;",
  "II - Descarga para jusante dos reservatórios Jaguari/Jacareí no rio Jaguari: 0,25 m³/s; e",
  "III - Descarga para jusante dos reservatórios Cachoeira/Atibainha no rio Atibaia: 0,25 m³/s.",
  "Art. 3º A operação do Sistema Cantareira observará a condição de armazenamento dos reservatórios e o período hidrológico do ano, buscando a racionalização do uso dos recursos hídricos e o atendimento ao uso múltiplo das águas.",
  "Parágrafo único. Para fins de operação do Sistema Cantareira, são definidos dois períodos hidrológicos:",
  "I - Período Úmido – de 1º de dezembro de um ano a 31 de maio do ano seguinte; e",
  "II - Período Seco – de 1º de junho a 30 de novembro do mesmo ano.",
  "Art. 4º Para a Região Metropolitana de São Paulo, o controle da captação de água do Sistema Cantareira, realizada pela SABESP, é a vazão captada na Estação Elevatória Santa Inês, que será autorizada mensalmente de acordo com as faixas do Sistema Cantareira a seguir estabelecidas:",
  "I - Faixa 1: Normal – volume útil acumulado igual ou maior que 60%;",
  "II - Faixa 2: Atenção – volume útil acumulado igual ou maior que 40% e menor que 60%;",
  "III - Faixa 3: Alerta – volume útil acumulado igual ou maior que 30% e menor que 40%;",
  "IV - Faixa 4: Restrição – volume útil acumulado igual ou maior que 20% e menor que 30%; e",
  "V - Faixa 5: Especial – volume acumulado inferior a 20% do volume útil.",
  "§ 1º Os limites de retirada pela Sabesp para a Região Metropolitana de São Paulo na Estação Elevatória Santa Inês, serão definidos mensalmente de acordo com a condição de armazenamento do Sistema Cantareira, nos limites máximos médios mensais a seguir estabelecidos:",
  "I - Faixa 1: Normal – 33,0 m³/s;",
  "II - Faixa 2: Atenção – 31,0 m³/s;",
  "III - Faixa 3: Alerta – 27,0 m³/s;",
  "IV - Faixa 4: Restrição – 23,0 m³/s; e",
  "V - Faixa 5: Especial – 15,5 m³/s.",
  "§ 2º Quando o Sistema Cantareira estiver operando nas Faixas 2 (Atenção), 3 (Alerta) e 4 (Restrição), as vazões bombeadas do reservatório de Jaguari, localizado na bacia do rio Paraíba do Sul, serão acrescidas às vazões máximas de retirada da SABESP, respeitado o limite outorgado.",
  "§ 3º Quando o Sistema Cantareira estiver operando na Faixa 5 (Especial), a definição e alocação das vazões bombeadas do reservatório de Jaguari, localizado na bacia do rio Paraíba do Sul, serão definidas pelos órgãos gestores para aumentar a segurança hídrica do sistema.",
  "§ 4º O limite de retirada pela Sabesp para a Região Metropolitana de São Paulo na Estação Elevatória Santa Inês na Faixa 5 (Especial) poderá ser reduzido pelos órgãos gestores, caso o volume observado do Sistema Cantareira em determinado mês seja inferior aos volumes definidos para o mês correspondente na curva guia constante do Anexo II desta Resolução.",
  "§ 5º Na eventualidade de um terceiro ano de operação contínua na Faixa 5 (Especial), o limite de retirada pela Sabesp para a Região Metropolitana de São Paulo na Estação Elevatória Santa Inês será definido pelos órgãos gestores.",
  "§ 6º Quando o Sistema Cantareira estiver operando na Faixa 1 (Normal), no período de 1º de outubro de um ano até 30 de abril do ano seguinte, a SABESP deverá operar o Sistema Cantareira observando suas regras de controle de cheia.",
  "Art. 5º A liberação de vazões para as Bacias PCJ será realizada de acordo com as condições de armazenamento do Sistema Cantareira, o período hidrológico do ano e as faixas estabelecidas nos incisos I a V do art. 4º desta Resolução.",
  "§ 1º Para o controle das vazões nas Bacias PCJ a jusante do Sistema Cantareira, ficam definidos os postos de controle de Captação de Valinhos (3D-007T) e de Atibaia (3E-063T), no rio Atibaia, e de Buenópolis (3D-009T), no rio Jaguari, e apresentados no Anexo I.",
  "§ 2º No Período Úmido, a liberação de vazões para as Bacias PCJ será realizada pela SABESP até às 8h00 do dia seguinte ao recebimento de comunicado do DAEE, que deverá ser simultaneamente encaminhado aos Comitês PCJ, para atender às vazões metas nos postos de controle definidos, em complementação às vazões incrementais nas porções de bacia a jusante dos reservatórios do Sistema Cantareira, de acordo com a sua condição de armazenamento, nos limites a seguir estabelecidos:",
  "I - Nas Faixas 1 e 2 (Normal e Atenção) – vazões médias móveis de quinze dias consecutivos mínimas de 12,0 m³/s no posto de controle de Captação de Valinhos, no rio Atibaia, de 3,0 m³/s no posto de controle de Atibaia, no rio Atibaia, e de 2,5 m³/s no posto de controle de Buenópolis, no rio Jaguari; e",
  "II - Nas Faixas 3 e 4 (Alerta e Restrição) - vazões médias móveis de quinze dias consecutivos mínimas de 11,0 m³/s no posto de controle de Captação de Valinhos, no rio Atibaia, de 2,0 m³/s no posto de controle de Atibaia, no rio Atibaia, e de 2,0 m³/s no posto de controle de Buenópolis, no rio Jaguari.",
  "§ 3º As vazões referidas nos incisos I e II do § 2º deste artigo, calculadas pelo DAEE e disponibilizadas em boletim diário, poderão sofrer variação momentânea desde que respeitada a vazão mínima média diária de 10,0 m³/s em Valinhos, de 2,0 m³/s em Buenópolis e de 2,0 m³/s em Atibaia.",
  "§ 4º A eventual ocorrência de vazões mínimas médias diárias inferiores aos valores estabelecidos no § 3° deste artigo, em decorrência de fatores externos excepcionais às regras de operação estabelecidas nesta Resolução, deverá ser devida e tecnicamente justificada à ANA e ao DAEE e comunicada aos Comitês PCJ.",
  "§ 5º No Período Seco, nas Faixas 1, 2, 3 e 4 (Normal, Atenção, Alerta e Restrição), será garantida uma vazão média, no período de 1º de junho a 30 de novembro, de 10,0 m³/s, equivalente a um volume de 158,1 hm³, a ser liberada do Sistema Cantareira para as Bacias PCJ.",
  "§ 6º A definição das vazões a serem liberadas para as Bacias PCJ mencionadas no § 5º deste artigo será realizada por meio de comunicado de representante indicado formalmente pelos Comitês das Bacias Hidrográficas dos Rios Piracicaba, Capivari e Jundiaí - Comitês PCJ, dirigido ao DAEE, observando:",
  "I - As condições hidrometeorológicas nas Bacias PCJ;",
  "II - As vazões mínimas instantâneas definidas nos incisos II e III do art. 2º desta Resolução e as vazões mínimas médias diárias de 10,0 m³/s no posto de controle de Captação de Valinhos, no rio Atibaia, de 2,0 m³/s no posto de controle de Atibaia, no rio Atibaia, e de 2,0 m³/s no posto de controle de Buenópolis, no rio Jaguari;",
  "III - A vazão média para o período de 1º de junho a 30 de novembro estabelecida no §5º deste artigo.",
  "§ 7º A liberação das vazões a que se refere o §5º será realizada pela SABESP até às 8h00 do dia seguinte ao recebimento do comunicado do DAEE.",
  "§ 8º Ao final do período seco, o volume disponibilizado e não utilizado pelas Bacias PCJ não será transferido para o ano seguinte.",
  "§ 9º Os volumes não utilizados pelas Bacias PCJ ao final do Período Seco poderão ser utilizados pela SABESP, mediante pagamento, conforme regra a ser definida entre os interessados.",
  "§ 10. Na Faixa 5 (Especial), independentemente do período do ano, deverá ser mantida uma vazão mínima média diária de 10,0 m³/s no posto de controle Captação de Valinhos, no rio Atibaia, e de 2,0 m³/s no posto de controle de Buenópolis, no rio Jaguari.",
  "§ 11. A liberação das vazões do Sistema Cantareira para atendimento ao disposto no §10 deste artigo será realizada pela SABESP até às 8h00 do dia seguinte ao recebimento de comunicado do DAEE.",
  "Art. 6º A faixa de operação do Sistema Cantareira a ser considerada para fins de definição das vazões a serem praticadas será estabelecida mensalmente pela ANA/DAEE, até o último dia útil do mês anterior.",
  "Parágrafo único. O estabelecimento das faixas 4 e 5 de operação, como faixa a ser considerada para fins de definição das vazões a serem praticadas, poderá ocorrer a qualquer momento, à critério da ANA/DAEE.",
  "Art. 7º Esta Resolução tem validade de 10 (dez) anos, a contar da data de sua publicação.",
  "Art. 8º Esta Resolução revoga a Resolução Conjunta ANA/DAEE nº 428, de 04 de agosto de 2004, publicada no DOU em 09 de agosto de 2004, seção 1, páginas 107 a 110.",
  "Art. 9º Esta Resolução entra em vigor na data de sua publicação.",
];
